import "../styles/global.css";
import { BoardContextProvider } from "@/lib/BoardContextProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-900 p-0 m-0 h-screen">
        <BoardContextProvider>{children}</BoardContextProvider>
      </body>
    </html>
  );
}
