import { NextRequest, NextResponse } from "next/server";
import "../styles/global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode;
  },
  req: NextRequest,
  res: NextResponse
) {
  return (
    <html lang="en">
      <body className="bg-gray-900 p-0 m-0 h-screen">{children}</body>
    </html>
  );
}
